description: "Testing github pages since 2023"
title: "Some github pages site"

# GFM will make URLs into links automatically,
# the default kramdown allows us to use the toc directive
# markdown: GFM
markdown: kramdown

theme: minima
logo: "/assets/images/logo.svg"

  #favicon: /assets/images/favicon.ico
  #apple_touch_icon: /assets/images/apple-touch-icon.png


menu:
  - title:             a link
    url:               https://example.com


related_posts: none

url: https://tgaff.github.io
baseurl: /some-gh-pages-site
