# This validates links on the site after it's deployed
# If you're operating on a fork, this won't work correctly for you.

name: Validate site links
on:
  deployment

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.8.0
        with:
          fail: true
          args: "--verbose --no-progress https://tgaff.github.io/some-gh-pages-site/"
