# This validates links on the site after it's deployed
# If you're operating on a fork, this won't work correctly for you.
name: Check links with muffet
on:
  deployment

jobs:
  my-broken-link-checker:
    name: Check broken links
    runs-on: ubuntu-latest
    steps:
      - name: Check
        uses: ruzickap/action-my-broken-link-checker@v2
        with:
          url: https://tgaff.github.io/some-gh-pages-site
          cmd_params: "--max-connections=3 --color=always"  # Check just one page
